show_views_column:
  default: false
  type: bool

show_likes_column:
  default: true
  type: bool

show_replies_column:
  default: true
  type: bool

show_activity_column:
  default: true
  type: bool